"""İstanbul landmarks: merge the per-landmark metadata written by the Blender generators (blender/landmarks_ist/*.py)
into assets/ist/landmarks/index.json (same schema as assets/sf/landmarks/index.json) and write data/ist/bridges.json
(CONTRACTS-IST.md §3: per bridge { id, name, x, z, axis, half, deck: [{ s, bottom, top }], towerTop, clear }).

Usage: GEO_REGION=ist .venv/bin/python tools/geo/landmarks_ist_index.py
"""
import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from geo import ASSETS_DIR, DATA_DIR, ROOT, REGION_ID  # noqa: E402

DIR = os.path.join(ASSETS_DIR, 'landmarks')
ORDER = ['bogazici', 'fsm', 'yss', 'galata_bridge', 'ataturk_bridge', 'halic_metro', 'halic_bridge', 'galata_kulesi',
         'kiz_kulesi', 'camlica_kulesi', 'camlica_camii', 'sultanahmet', 'ayasofya', 'suleymaniye', 'yeni_cami', 'topkapi',
         'dolmabahce', 'rumeli_hisari', 'haydarpasa', 'sapphire', 'skyline']


def main():
    assert REGION_ID == 'ist', 'run with GEO_REGION=ist'
    items = []
    for p in sorted(glob.glob(os.path.join(DIR, '*.json'))):
        if os.path.basename(p) == 'index.json':
            continue
        d = json.load(open(p))
        if not d.get('lods'):
            continue
        missing = [l['url'] for l in d['lods'] if not os.path.exists(os.path.join(ROOT, l['url']))]
        if missing:
            print('skip', d['id'], 'missing', missing)
            continue
        items.append(d)
    items.sort(key=lambda d: (ORDER.index(d['id']) if d['id'] in ORDER else 99, d['id']))
    bridges = []
    for d in items:
        b = d.pop('bridge', None)
        if b:
            bridges.append({'id': d['id'], 'name': d['name'], **b})
    out = {'version': 1, 'map': 'ist',
           'note': 'Generated by tools/geo/landmarks_ist_index.py from the Blender generators (blender/landmarks_ist).',
           'landmarks': items}
    json.dump(out, open(os.path.join(DIR, 'index.json'), 'w'), separators=(',', ':'))
    bj = {'version': 1, 'note': 'Generated by tools/geo/landmarks_ist_index.py. x, z: main-span centre (local m); axis: '
          'heading of the deck in the local map frame (deg, 0 = grid north, clockwise; the model +Y); half: tower '
          'spacing / 2 (main span / 2); deck: underside (bottom) and top of the deck incl. barriers, m MSL, every 25 m '
          'at s m along the axis from x, z; towerTop: m MSL; clear: lowest underside within |s| <= half - 40.',
          'bridges': bridges}
    json.dump(bj, open(os.path.join(DATA_DIR, 'bridges.json'), 'w'), indent=1)
    tot = 0
    tris0 = 0
    for d in items:
        size = sum(os.path.getsize(os.path.join(ROOT, l['url'])) for l in d['lods'])
        tot += size
        tris0 += d.get('tris', {}).get('0', 0)
        print(f"{d['id']:16s} {d['name']:30s} tris={d.get('tris')} coll={len(d.get('collision', []))} "
              f"lights={len(d.get('lights', []))} {size / 1e6:.2f} MB")
    tex = sum(os.path.getsize(p) for p in glob.glob(os.path.join(DIR, '**', '*'), recursive=True)
              if os.path.isfile(p) and '/_' not in p.replace(DIR, ''))
    print(f'{len(items)} landmarks, GLBs {tot / 1e6:.1f} MB, published dir {tex / 1e6:.1f} MB, LOD0 tris {tris0}; '
          f'{len(bridges)} bridges -> data/ist/bridges.json')


if __name__ == '__main__':
    main()
