"""W3 landmarks: merge the per-landmark metadata written by the Blender builders into assets/sf/landmarks/index.json.

Each builder writes assets/sf/landmarks/<id>.json = { id, name (Turkish), origin {x,z}, heading, base
('absolute' | 'terrain'), lods [{url, dist}], bounds {min,max} (Three local), collision [...], lights [...], tris,
optional instances [[x,y,z,yaw,scale],...], footprint [[x,z],...] }.
Usage: .venv/bin/python tools/geo/landmarks_index.py
"""
import glob
import json
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
DIR = os.path.join(ROOT, 'assets', 'sf', 'landmarks')
ORDER = ['golden_gate', 'bay_bridge', 'transamerica', 'salesforce', 'coit_tower', 'ferry_building', 'sutro_tower',
         'alcatraz', 'palace_of_fine_arts', 'city_hall', 'oracle_park', 'chase_center', 'painted_ladies', 'fort_point',
         'pier_39', 'oakland_cranes', 'skyline']


def main():
    items = []
    for p in sorted(glob.glob(os.path.join(DIR, '*.json'))):
        if os.path.basename(p) == 'index.json':
            continue
        d = json.load(open(p))
        if 'lods' not in d or not d['lods']:
            continue
        missing = [l['url'] for l in d['lods'] if not os.path.exists(os.path.join(ROOT, l['url']))]
        if missing:
            print('skip', d['id'], 'missing', missing)
            continue
        items.append(d)
    items.sort(key=lambda d: ORDER.index(d['id']) if d['id'] in ORDER else 99)
    out = {'version': 1, 'note': 'Generated by tools/geo/landmarks_index.py from the Blender builders (W3).',
           'landmarks': items}
    json.dump(out, open(os.path.join(DIR, 'index.json'), 'w'), separators=(',', ':'))
    tot = 0
    for d in items:
        size = sum(os.path.getsize(os.path.join(ROOT, l['url'])) for l in d['lods'])
        tot += size
        print(f"{d['id']:22s} {d['name']:28s} lods={len(d['lods'])} tris={d.get('tris')} coll={len(d.get('collision', []))} "
              f"lights={len(d.get('lights', []))} {size / 1e6:.2f} MB")
    print(f'{len(items)} landmarks, {tot / 1e6:.1f} MB total')


if __name__ == '__main__':
    main()
