#!/bin/bash
# Staging (staging.fs.erenailab.com) is only reachable from allow-listed IPv4 addresses.
# The list lives outside the repo: ~/.config/gokyuzu/staging_ips (one IP per line).
# Usage: tools/deploy/staging_access.sh            → adds your current public IP and republishes the CloudFront Function
#        tools/deploy/staging_access.sh --list     → shows the allow list
set -euo pipefail
export AWS_PROFILE=gokyuzu-admin
LIST=~/.config/gokyuzu/staging_ips
FN=gokyuzu-staging-ip-allow
mkdir -p "$(dirname "$LIST")"; touch "$LIST"; chmod 600 "$LIST"
if [ "${1:-}" = "--list" ]; then cat "$LIST"; exit 0; fi
ME=$(curl -s -4 https://checkip.amazonaws.com | tr -d '[:space:]')
grep -qx "$ME" "$LIST" || echo "$ME" >> "$LIST"
IPS=$(grep -E '^[0-9.]+$' "$LIST" | sed "s/.*/'&'/" | paste -sd, -)
CODE=$(mktemp)
cat > "$CODE" <<JS
// Generated by tools/deploy/staging_access.sh — do not edit in the console.
var ALLOW = [$IPS];
function handler(event) {
  if (ALLOW.indexOf(event.viewer.ip) === -1) {
    return { statusCode: 403, statusDescription: 'Forbidden',
      headers: { 'content-type': { value: 'text/plain; charset=utf-8' }, 'cache-control': { value: 'no-store' } },
      body: { encoding: 'text', data: 'Bu test ortamina yalnizca yetkili IP adreslerinden erisilebilir.' } };
  }
  return event.request;
}
JS
if aws cloudfront describe-function --name $FN >/dev/null 2>&1; then
  ETAG=$(aws cloudfront describe-function --name $FN --query ETag --output text)
  ETAG=$(aws cloudfront update-function --name $FN --if-match "$ETAG" --function-config "Comment=Gokyuzu staging IP allow-list,Runtime=cloudfront-js-2.0" --function-code "fileb://$CODE" --query ETag --output text)
else
  ETAG=$(aws cloudfront create-function --name $FN --function-config "Comment=Gokyuzu staging IP allow-list,Runtime=cloudfront-js-2.0" --function-code "fileb://$CODE" --query ETag --output text)
fi
aws cloudfront publish-function --name $FN --if-match "$ETAG" >/dev/null
rm -f "$CODE"
echo "Staging erişimi güncellendi: $(grep -cE '^[0-9.]+$' "$LIST") IP izinli (sizinki: $ME)"
