"""Materials (glTF-compatible Principled BSDF). Textures come from build/tex (generated by textures.py)."""
import os
import bpy
import geo

HERE = os.path.dirname(os.path.abspath(__file__))
TEX = os.path.join(HERE, 'build', 'tex')


LOD = False


def _img(name):
    if LOD:
        if not name.endswith('_color.jpg'):
            return None                       # detail maps are dropped in the static LOD
        name = 'lod_' + name
    p = os.path.join(TEX, name)
    if os.path.exists(p):
        return bpy.data.images.load(p, check_existing=True)
    return None


def build_materials(preview=False, lod=False):
    global LOD
    LOD = lod
    P = geo.principled
    m = {}
    fus_c, fus_r, fus_n = _img('fuselage_color.jpg'), _img('fuselage_orm.png'), _img('fuselage_normal.png')
    m['fuselage'] = P('fuselage', color=(0.92, 0.92, 0.93), roughness=0.32, tex=fus_c, rough_tex=fus_r,
                      normal_tex=fus_n, normal_strength=0.6)
    m['belly'] = P('belly', color=(0.06, 0.13, 0.33), roughness=0.35, tex=_img('belly_color.jpg'))
    wc, wr = _img('wing_color.jpg'), _img('wing_orm.png')
    m['wing'] = P('wing', color=(0.72, 0.74, 0.76), roughness=0.45, tex=wc, rough_tex=wr, normal_tex=_img('wing_normal.png'),
                  normal_strength=0.5)
    m['wing_le'] = P('wing_le', color=(0.80, 0.81, 0.82), metallic=0.85, roughness=0.28)
    m['tail'] = P('tail', color=(0.05, 0.12, 0.32), roughness=0.3, tex=_img('tail_color.jpg'), rough_tex=_img('tail_orm.png'))
    m['htail'] = P('htail', color=(0.72, 0.74, 0.76), roughness=0.45, tex=_img('htail_color.jpg'))
    m['nacelle'] = P('nacelle', color=(0.05, 0.12, 0.32), roughness=0.3, tex=_img('nacelle_color.jpg'))
    m['inlet_lip'] = P('inlet_lip', color=(0.86, 0.87, 0.88), metallic=1.0, roughness=0.18)
    m['engine_inner'] = P('engine_inner', color=(0.30, 0.31, 0.33), roughness=0.55, metallic=0.2)
    m['fan'] = P('fan', color=(0.20, 0.21, 0.23), metallic=0.6, roughness=0.35)
    m['spinner'] = P('spinner', color=(0.55, 0.56, 0.58), metallic=0.9, roughness=0.3, tex=_img('spinner_color.jpg'))
    m['core'] = P('core', color=(0.45, 0.46, 0.48), metallic=0.8, roughness=0.4)
    m['exhaust'] = P('exhaust', color=(0.22, 0.20, 0.19), metallic=0.9, roughness=0.55)
    m['pylon'] = P('pylon', color=(0.90, 0.90, 0.91), roughness=0.4)
    m['gear'] = P('gear', color=(0.74, 0.75, 0.76), metallic=0.3, roughness=0.45)
    m['gear_chrome'] = P('gear_chrome', color=(0.9, 0.9, 0.92), metallic=1.0, roughness=0.12)
    m['tire'] = P('tire', color=(0.035, 0.035, 0.038), roughness=0.85, tex=_img('tire_color.jpg'))
    m['hub'] = P('hub', color=(0.62, 0.63, 0.65), metallic=0.7, roughness=0.4)
    m['gear_bay'] = P('gear_bay', color=(0.16, 0.18, 0.16), roughness=0.75, double_sided=True)
    m['leg_door'] = P('leg_door', color=(0.52, 0.55, 0.58), roughness=0.45)
    m['frame_paint'] = P('frame_paint', color=(0.018, 0.02, 0.023), roughness=0.3)
    m['dark'] = P('dark', color=(0.02, 0.02, 0.02), roughness=0.8)
    m['glass'] = P('cockpit_glass', color=(0.02, 0.03, 0.035), roughness=0.04, metallic=0.0, alpha=1.0 if lod else 0.9)
    m['light_red'] = P('light_red', color=(0.6, 0.02, 0.02), emission=(1.0, 0.05, 0.03), emission_strength=4.0, roughness=0.2)
    m['light_green'] = P('light_green', color=(0.02, 0.6, 0.1), emission=(0.1, 1.0, 0.3), emission_strength=4.0, roughness=0.2)
    m['light_white'] = P('light_white', color=(0.9, 0.9, 0.9), emission=(1, 1, 1), emission_strength=2.0, roughness=0.1)
    m['lens'] = P('lens', color=(0.85, 0.87, 0.9), metallic=0.0, roughness=0.05)
    m['antenna'] = P('antenna', color=(0.9, 0.9, 0.91), roughness=0.4)
    m['probe'] = P('probe', color=(0.7, 0.7, 0.72), metallic=0.9, roughness=0.3)
    m['cascade'] = P('cascade', color=(0.08, 0.08, 0.09), metallic=0.5, roughness=0.6)
    m['wiper'] = P('wiper', color=(0.03, 0.03, 0.03), roughness=0.5)
    return m
