"""F-16C cockpit geometry (wave 6 rebuild). Pure numpy; build.py turns the parts into Blender objects.

Output of build(): dict part key -> MeshData (drawing-frame verts converted to Blender, faces, uvs, name=key)
  'art:<panel>'  faces that look along the panel normal, UV = panel coords -> build/art/<panel>.png
  'm:<material>' everything else (constant colour; UVs are generated by the bake step)
  keys ending in '|lite' hold the faces that also go into the light stand-in (interior_lite)
screens: dict screen_* -> MeshData (UV 0..1), glass: dict name -> MeshData (transparent parts)
"""
import math
import numpy as np
from f16_geom import MeshData, to_blender
import f16_ck_layout as CL
import f16_cockpit_layout as OLD          # seat hip / back angle shared with the pilot figure
import f16_parts as PT
import f16_fuselage as FU

TAU = 2 * math.pi


def V3(*a):
    return np.array(a, float)


class Parts:
    def __init__(self):
        self.parts = {}
        self.screens = {}
        self.glass = {}

    def _md(self, key):
        return self.parts.setdefault(key, dict(v=[], f=[], uv=[]))

    def add(self, key, verts, faces, uvs=None, lite=False):
        """verts: (N,3) drawing frame; faces: list of index tuples; uvs: per-face list of (u,v) or None."""
        k = key + ('|lite' if lite else '')
        m = self._md(k)
        off = sum(len(x) for x in m['v'])
        m['v'].append(np.asarray(verts, float).reshape(-1, 3))
        for i, f in enumerate(faces):
            m['f'].append(tuple(int(j) + off for j in f))
            m['uv'].append(uvs[i] if uvs is not None else [(0.0, 0.0)] * len(f))

    def meshdata(self):
        out = {}
        for k, m in self.parts.items():
            if not m['f']:
                continue
            V = np.concatenate(m['v'])
            out[k] = MeshData(to_blender(V[:, 0], V[:, 1], V[:, 2]), m['f'], m['uv'], k)
        return out


def _single(verts, faces, uvs, name):
    V = np.asarray(verts, float)
    return MeshData(to_blender(V[:, 0], V[:, 1], V[:, 2]), faces, uvs, name)


# ----------------------------------------------------------------------------------------------------------------------
# local primitive generators: return (V (N,3), faces). Coordinates are "local" (x, y, z) in whatever frame the caller uses.
def g_box(x0, y0, z0, x1, y1, z1):
    V = [(x, y, z) for z in (z0, z1) for y in (y0, y1) for x in (x0, x1)]
    # index = zi*4 + yi*2 + xi
    F = [(0, 2, 3, 1), (4, 5, 7, 6), (0, 1, 5, 4), (2, 6, 7, 3), (0, 4, 6, 2), (1, 3, 7, 5)]
    return np.array(V, float), F


def g_cyl(r0, r1, z0, z1, n=16, cap0=True, cap1=True, x=0.0, y=0.0, rot=0.0):
    V = []
    for z, r in ((z0, r0), (z1, r1)):
        for k in range(n):
            a = TAU * k / n + rot
            V.append((x + r * math.cos(a), y + r * math.sin(a), z))
    F = [(k, (k + 1) % n, n + (k + 1) % n, n + k) for k in range(n)]
    if cap0:
        F.append(tuple(range(n))[::-1])
    if cap1:
        F.append(tuple(range(n, 2 * n)))
    return np.array(V, float), F


def g_lathe(profile, n=16, x=0.0, y=0.0, cap_top=True):
    """profile: list of (r, z) from bottom to top; revolve about local z at (x, y)."""
    V = []
    for r, z in profile:
        for k in range(n):
            a = TAU * k / n
            V.append((x + r * math.cos(a), y + r * math.sin(a), z))
    F = []
    m = len(profile)
    for i in range(m - 1):
        for k in range(n):
            a, b = i * n + k, i * n + (k + 1) % n
            F.append((a, b, b + n, a + n))
    if cap_top and profile[-1][0] > 1e-6:
        F.append(tuple(range((m - 1) * n, m * n)))
    return np.array(V, float), F


def g_fluted(r, z0, z1, flutes=18, depth=0.12, x=0.0, y=0.0, top_chamfer=0.25):
    """Fluted knob: star-shaped prism with a chamfered top."""
    n = flutes * 2
    V = []
    rings = [(z0, 1.0), (z1 - r * top_chamfer * 0.6, 1.0), (z1, 1.0 - top_chamfer)]
    for z, s in rings:
        for k in range(n):
            a = TAU * k / n
            rr = r * s * (1.0 if k % 2 == 0 else 1.0 - depth)
            V.append((x + rr * math.cos(a), y + rr * math.sin(a), z))
    F = []
    for i in range(len(rings) - 1):
        for k in range(n):
            a, b = i * n + k, i * n + (k + 1) % n
            F.append((a, b, b + n, a + n))
    F.append(tuple(range(2 * n, 3 * n)))
    return np.array(V, float), F


def g_tube(path, r, n=10, closed=False, caps=True):
    """Sweep a circle of radius r (scalar or per-point list) along a polyline (N,3)."""
    P = np.asarray(path, float)
    N = len(P)
    rs = np.full(N, r) if np.isscalar(r) else np.asarray(r, float)
    T = np.zeros_like(P)
    for i in range(N):
        if closed:
            T[i] = P[(i + 1) % N] - P[(i - 1) % N]
        else:
            T[i] = P[min(i + 1, N - 1)] - P[max(i - 1, 0)]
        T[i] /= np.linalg.norm(T[i]) + 1e-12
    ref = np.array([0, 0, 1.0]) if abs(T[0][2]) < 0.9 else np.array([1.0, 0, 0])
    U = []
    u = np.cross(T[0], ref); u /= np.linalg.norm(u)
    for i in range(N):
        u = u - T[i] * np.dot(u, T[i]); u /= np.linalg.norm(u) + 1e-12
        U.append(u.copy())
    V = []
    for i in range(N):
        w = np.cross(T[i], U[i])
        for k in range(n):
            a = TAU * k / n
            V.append(P[i] + rs[i] * (math.cos(a) * U[i] + math.sin(a) * w))
    F = []
    segs = N if closed else N - 1
    for i in range(segs):
        i2 = (i + 1) % N
        for k in range(n):
            a, b = i * n + k, i * n + (k + 1) % n
            F.append((a, b, i2 * n + (k + 1) % n, i2 * n + k))
    if caps and not closed:
        F.append(tuple(range(n))[::-1])
        F.append(tuple(range((N - 1) * n, N * n)))
    return np.array(V, float), F


def g_rrect_prism(w, h, r, z0, z1, n=4, x=0.0, y=0.0):
    """Rounded-rectangle prism (bezels, key caps)."""
    pts = []
    r = min(r, w / 2 - 1e-5, h / 2 - 1e-5)
    for cx, cy, a0 in ((w / 2 - r, h / 2 - r, 0), (-w / 2 + r, h / 2 - r, 90), (-w / 2 + r, -h / 2 + r, 180), (w / 2 - r, -h / 2 + r, 270)):
        for k in range(n + 1):
            a = math.radians(a0 + 90 * k / n)
            pts.append((x + cx + r * math.cos(a), y + cy + r * math.sin(a)))
    m = len(pts)
    V = [(px, py, z0) for px, py in pts] + [(px, py, z1) for px, py in pts]
    F = [(k, (k + 1) % m, m + (k + 1) % m, m + k) for k in range(m)]
    F.append(tuple(range(m))[::-1])
    F.append(tuple(range(m, 2 * m)))
    return np.array(V, float), F


def g_flange(dia, sw, sh, z0, z1, depth_cup, n=32, x=0.0, y=0.0):
    """Square instrument flange (sw x sh) with a round hole of diameter dia and an inner cup wall back to z0-depth_cup."""
    r = dia / 2
    V, F = [], []
    ring_in, ring_out = [], []
    for k in range(n):
        a = TAU * k / n
        c, s = math.cos(a), math.sin(a)
        # ray to the rectangle
        tx = (sw / 2) / abs(c) if abs(c) > 1e-9 else 1e9
        ty = (sh / 2) / abs(s) if abs(s) > 1e-9 else 1e9
        t = min(tx, ty)
        ring_in.append((x + r * c, y + r * s))
        ring_out.append((x + t * c, y + t * s))
    # front face (z1): quads between inner circle and outer square
    for (px, py) in ring_in:
        V.append((px, py, z1))
    for (px, py) in ring_out:
        V.append((px, py, z1))
    for k in range(n):
        k2 = (k + 1) % n
        F.append((k, k2, n + k2, n + k))
    # outer side walls (z0..z1)
    base = len(V)
    for (px, py) in ring_out:
        V.append((px, py, z0))
    for k in range(n):
        k2 = (k + 1) % n
        F.append((n + k, n + k2, base + k2, base + k))
    # inner cup wall (z1 .. z0 - depth_cup)
    base2 = len(V)
    for (px, py) in ring_in:
        V.append((px, py, z0 - depth_cup))
    for k in range(n):
        k2 = (k + 1) % n
        F.append((k2, k, base2 + k, base2 + k2))
    F = [tuple(f)[::-1] for f in F]
    return np.array(V, float), F


def g_rect_ring(ow, oh, iw, ih, z0, z1, well, n=64, x=0.0, y=0.0, p_out=7.0):
    """Display bezel: rounded outer rectangle (superellipse) with a rectangular window, plus the window's well walls
    back to z1 - well. Faces oriented: front +z, outer walls outward, well walls inward."""
    def sup(a, b, t, p):
        c, s_ = math.cos(t), math.sin(t)
        r = (abs(c / a) ** p + abs(s_ / b) ** p) ** (-1.0 / p)
        return r * c, r * s_
    V, F = [], []
    for k in range(n):
        t = TAU * k / n
        ix, iy = sup(iw / 2, ih / 2, t, 60.0)
        ox, oy = sup(ow / 2, oh / 2, t, p_out)
        V += [(x + ix, y + iy, z1), (x + ox, y + oy, z1), (x + ox, y + oy, z0), (x + ix, y + iy, z1 - well)]
    for k in range(n):
        a, b = 4 * k, 4 * ((k + 1) % n)
        F.append((a, b, b + 1, a + 1))          # front ring
        F.append((a + 1, b + 1, b + 2, a + 2))  # outer wall
        F.append((a + 3, b + 3, b, a))          # well wall
    V = np.array(V, float)
    out = []
    cen = np.array([x, y, 0.0])
    for i, f in enumerate(F):
        P = V[list(f)]
        nrm = face_normal(P)
        kind = i % 3
        if kind == 0:
            ok = nrm[2] > 0
        else:
            rad = P.mean(0) - cen; rad[2] = 0
            ok = np.dot(nrm, rad) > 0 if kind == 1 else np.dot(nrm, rad) < 0
        out.append(tuple(f) if ok else tuple(f)[::-1])
    return V, out


def g_torus_arc(R, r, a0, a1, n_major=16, n_minor=8, x=0.0, y=0.0, z=0.0):
    V = []
    for i in range(n_major + 1):
        a = a0 + (a1 - a0) * i / n_major
        cx, cy = x + R * math.cos(a), y + R * math.sin(a)
        for k in range(n_minor):
            b = TAU * k / n_minor
            rr = R + r * math.cos(b)
            V.append((x + rr * math.cos(a), y + rr * math.sin(a), z + r * math.sin(b)))
    F = []
    for i in range(n_major):
        for k in range(n_minor):
            a, b = i * n_minor + k, i * n_minor + (k + 1) % n_minor
            F.append((a, b, b + n_minor, a + n_minor))
    return np.array(V, float), F


def face_normal(P):
    n = np.zeros(3)
    for i in range(len(P)):
        a, b = P[i], P[(i + 1) % len(P)]
        n += np.cross(a, b)
    l = np.linalg.norm(n)
    return n / l if l > 1e-15 else n


def orient_out(V, F, center=None):
    """Flip faces so their normals point away from the centroid (closed convex-ish shapes)."""
    V = np.asarray(V, float)
    c = V.mean(0) if center is None else np.asarray(center, float)
    out = []
    for f in F:
        P = V[list(f)]
        if np.dot(face_normal(P), P.mean(0) - c) < 0:
            f = tuple(f)[::-1]
        out.append(tuple(f))
    return out


# ----------------------------------------------------------------------------------------------------------------------
class PanelCtx:
    """Adds item geometry in panel-local coords (x=u, y=v, z=d toward the pilot) to the parts, routing faces."""

    def __init__(self, parts, P):
        self.parts = parts
        self.P = P
        self.f = P['f']
        self.w, self.h = P['w'], P['h']
        self.art = 'art:' + P['name']
        self.lite = P.get('lite', True)
        M = np.array([self.f.u, self.f.v, self.f.n], float)      # rows
        self.M = M
        self.c = np.array(self.f.c, float)

    def uv(self, x, y):
        return ((x + self.w / 2) / self.w, (y + self.h / 2) / self.h)

    def to_world(self, V):
        V = np.asarray(V, float)
        return self.c + V @ self.M

    def add(self, V, F, mat, art_front=True, lite=False, thr=0.96, orient=True, center=None):
        V = np.asarray(V, float)
        if orient:
            F = orient_out(V, F, center)
        W = self.to_world(V)
        art_f, art_uv, oth_f = [], [], []
        for f in F:
            P = V[list(f)]
            nz = face_normal(P)[2]
            if art_front and nz > thr:
                art_f.append(f)
                art_uv.append([self.uv(V[i][0], V[i][1]) for i in f])
            else:
                oth_f.append(f)
        if art_f:
            self.parts.add(self.art, W, art_f, art_uv, lite=lite)
        if oth_f:
            self.parts.add('m:' + mat, W, oth_f, None, lite=lite)


# ----------------------------------------------------------------------------------------------------------------------
def build_panel(parts, P):
    ctx = PanelCtx(parts, P)
    w, h = P['w'], P['h']
    # face (outline polygon or rect), as a small grid for nicer baking
    outline = P['outline'] or [(-w / 2, -h / 2), (w / 2, -h / 2), (w / 2, h / 2), (-w / 2, h / 2)]
    V = [(x, y, 0.0) for x, y in outline]
    cen = np.mean(np.array(outline), 0)
    Vf = V + [(cen[0], cen[1], 0.0)]
    m = len(outline)
    F = [(k, (k + 1) % m, m) for k in range(m)]
    uvs = [[ctx.uv(Vf[i][0], Vf[i][1]) for i in f] for f in F]
    parts.add(ctx.art, ctx.to_world(Vf), F, uvs, lite=ctx.lite)
    # back skirt (panel thickness) down to -depth
    d = P['depth']
    Vs = [(x, y, 0.0) for x, y in outline] + [(x, y, -d) for x, y in outline]
    Fs = [((k + 1) % m, k, m + k, m + (k + 1) % m) for k in range(m)]
    parts.add('m:' + P.get('base', 'panel'), ctx.to_world(Vs), Fs, None, lite=ctx.lite)
    for it in P['items']:
        ITEM_BUILDERS.get(it['k'], lambda c, i: None)(ctx, it)
    return ctx


def it_gauge(ctx, it):
    x, y, dia = it['u'], it['v'], it['dia']
    if it['flange'] == 'tall':
        sw, sh = dia + 0.006, dia * 2.9
        V, F = g_rrect_prism(sw, sh, 0.003, 0.0, 0.006, x=x, y=y)
        ctx.add(V, F, 'black')
        return
    sw = sh = dia + 0.006
    V, F = g_flange(dia, sw, sh, 0.0, 0.007, 0.0, n=36, x=x, y=y)
    ctx.add(V, F, 'black', orient=False)
    ctx.parts.glass.setdefault('gauge_glass', []).append(
        ctx.to_world(np.array([(x + dia / 2 * math.cos(TAU * k / 24), y + dia / 2 * math.sin(TAU * k / 24), 0.0045) for k in range(24)])))
    kn = it.get('knob')
    if kn:
        where, r = kn
        pos = []
        if where in ('ll', 'both'):
            pos.append((x - sw / 2 + r * 0.9, y - sh / 2 + r * 0.9))
        if where in ('lr', 'both'):
            pos.append((x + sw / 2 - r * 0.9, y - sh / 2 + r * 0.9))
        for px, py in pos:
            V, F = g_fluted(r, 0.006, 0.017, flutes=14, x=px, y=py)
            ctx.add(V, F, 'black', orient=False)


def it_key(ctx, it):
    x, y, w, h = it['u'], it['v'], it['w'], it['h']
    d = it['depth']
    if it['style'] == 'round':
        # recessed collar + round cap
        V, F = g_cyl(w / 2 + 0.0015, w / 2 + 0.0015, 0.0, d * 0.5, n=20, cap0=False, x=x, y=y)
        ctx.add(V, F, 'black', art_front=False)
        V, F = g_cyl(w / 2 * 0.86, w / 2 * 0.86, 0.0, d, n=20, cap0=False, x=x, y=y)
        ctx.add(V, F, 'rubber', orient=False)
        return
    V, F = g_rrect_prism(w, h, min(w, h) * 0.12, 0.0, d, n=2, x=x, y=y)
    ctx.add(V, F, 'rubber', orient=False)


def it_light(ctx, it):
    x, y, w, h = it['u'], it['v'], it['w'], it['h']
    V, F = g_rrect_prism(w + 0.002, h + 0.002, 0.001, 0.0, it['depth'], n=1, x=x, y=y)
    ctx.add(V, F, 'black', orient=False)


def it_knob(ctx, it):
    x, y, r = it['u'], it['v'], it['r']
    st = it['style']
    if st == 'bar':
        # skirt + pointer bar knob ("chicken head")
        V, F = g_cyl(r * 1.05, r * 1.05, 0.0, 0.004, n=20, cap0=False, x=x, y=y)
        ctx.add(V, F, 'black', orient=False)
        V, F = g_box(-r * 1.25, -r * 0.33, 0.004, r * 1.25, r * 0.33, 0.004 + r * 1.3)
        a = math.radians(it.get('ang', 0.0) + 90)
        R = np.array([[math.cos(a), -math.sin(a), 0], [math.sin(a), math.cos(a), 0], [0, 0, 1]])
        V = V @ R.T + np.array([x, y, 0])
        ctx.add(V, F, 'black')
        return
    if st == 'wheelv':
        # vertical thumbwheel (pitch trim) in a slot
        V, F = g_box(x - r * 0.9, y - r * 1.4, 0.0, x + r * 0.9, y + r * 1.4, 0.002)
        ctx.add(V, F, 'black')
        V, F = g_cyl(r, r, -r * 0.45, r * 0.45, n=24, x=0.0, y=0.0)
        V = V[:, [2, 0, 1]] + np.array([x, y, 0.001])     # axis along u
        ctx.add(V, F, 'metal', art_front=False)
        return
    V, F = g_fluted(r, 0.0, it.get('h', 0.014) * (r / 0.01) ** 0.5, flutes=16, x=x, y=y)
    ctx.add(V, F, 'black', orient=False)


def it_toggle(ctx, it):
    x, y, s = it['u'], it['v'], it['size']
    # hex nut + bushing
    V, F = g_cyl(0.0042 * s, 0.0042 * s, 0.0, 0.0022 * s, n=6, cap0=False, x=x, y=y, rot=math.pi / 6)
    ctx.add(V, F, 'metal', orient=False)
    V, F = g_cyl(0.0026 * s, 0.0026 * s, 0.0022 * s, 0.0045 * s, n=10, cap0=False, x=x, y=y)
    ctx.add(V, F, 'metal', art_front=False, orient=False)
    ang = {'up': 22, 'dn': -22, 'mid': 0}[it['pos']]
    a = math.radians(ang)
    L = 0.017 * s
    p0 = np.array([x, y, 0.004 * s])
    dirv = np.array([0.0, math.sin(a), math.cos(a)])
    p1 = p0 + dirv * L
    V, F = g_tube([p0, p0 + dirv * L * 0.5, p1], [0.0012 * s, 0.0014 * s, 0.0019 * s], n=8)
    ctx.add(V, F, 'metal', art_front=False, orient=False)
    V, F = g_lathe([(0.0, -0.0022 * s), (0.0019 * s, -0.0012 * s), (0.0022 * s, 0.0), (0.0019 * s, 0.0012 * s), (0.0, 0.0022 * s)], n=10)
    # orient the tip ball along dirv
    V = V + p1
    ctx.add(V, F, 'metal', art_front=False, orient=False)
    g = it.get('guard')
    if g:
        # hinged cover (closed over the switch, open side toward the pilot's reach): U-shaped box
        col = 'red' if g == 'red' else 'yellow'
        gw, gh, gd = 0.014 * s, 0.026 * s, 0.022 * s
        yb = y + (0.002 if ang >= 0 else -0.002)
        for sx in (-1, 1):
            V, F = g_box(x + sx * gw / 2 - 0.0008, yb - gh / 2, 0.0, x + sx * gw / 2 + 0.0008, yb + gh / 2, gd)
            ctx.add(V, F, col, art_front=False)
        V, F = g_box(x - gw / 2 - 0.0008, yb - gh / 2, gd - 0.0016, x + gw / 2 + 0.0008, yb + gh / 2, gd)
        ctx.add(V, F, col, art_front=False)
        V, F = g_box(x - gw / 2 - 0.0008, yb + gh / 2 - 0.0016, 0.0, x + gw / 2 + 0.0008, yb + gh / 2, gd)
        ctx.add(V, F, col, art_front=False)


def it_display(ctx, it):
    x, y = it['u'], it['v']
    bw, bh, sw, sh, d = it['bw'], it['bh'], it['sw'], it['sh'], it['depth']
    sx, sy = x + it['soff'][0], y + it['soff'][1]
    ds = d - 0.004
    # bezel = frame around the display window (front face painted), window well 4 mm deep
    V, F = g_rect_ring(bw, bh, sw + 0.004, sh + 0.004, 0.0, d, 0.004, n=72, x=x, y=y)
    ctx.add(V, F, 'black', orient=False, lite=True)
    # back of the well (behind the screen) so the display never shows a hole
    Vb, Fb = g_box(sx - sw / 2 - 0.002, sy - sh / 2 - 0.002, 0.0, sx + sw / 2 + 0.002, sy + sh / 2 + 0.002, ds - 0.0005)
    ctx.add(Vb, Fb, 'black', art_front=False, lite=True)
    # screen quad (UV v = 1 at the bottom: glTF flips v and the avionics canvas textures keep flipY = true)
    Vs = [(sx - sw / 2, sy - sh / 2, ds), (sx + sw / 2, sy - sh / 2, ds), (sx + sw / 2, sy + sh / 2, ds), (sx - sw / 2, sy + sh / 2, ds)]
    ctx.parts.screens[it['name']] = _single(ctx.to_world(Vs), [(0, 1, 2, 3)], [[(0, 1), (1, 1), (1, 0), (0, 0)]], it['name'])
    if it['osb']:
        for bx, by, kw, kh in CL.osb_positions(it):
            V, F = g_rrect_prism(kw, kh, 0.0012, d, d + 0.0035, n=1, x=bx, y=by)
            ctx.add(V, F, 'rubber', orient=False)
        # rocker switches in the corners (GAIN / SYM / BRT / CON)
        for cx, cy in ((-1, 1), (1, 1), (-1, -1), (1, -1)):
            bx, by = x + cx * (bw / 2 - 0.0095), y + cy * (bh / 2 - 0.0095)
            V, F = g_rrect_prism(0.0085, 0.0085, 0.002, d, d + 0.003, n=1, x=bx, y=by)
            ctx.add(V, F, 'rubber', orient=False)


def it_wheel(ctx, it):
    x, y, r, w = it['u'], it['v'], it['r'], it['w']
    # ribbed thumbwheel, axis along v, half sunk into the face
    V, F = g_cyl(r, r, -w / 2, w / 2, n=28)
    V = V[:, [0, 2, 1]]                  # axis -> y
    V[:, 0] += x
    V[:, 1] += y
    V[:, 2] += -r * 0.35
    ctx.add(V, F, 'lgray', art_front=False)


def it_special(ctx, it):
    fn = SPECIALS.get(it['name'])
    if fn:
        fn(ctx, it)


ITEM_BUILDERS = dict(gauge=it_gauge, key=it_key, light=it_light, knob=it_knob, toggle=it_toggle, display=it_display,
                     wheel=it_wheel, special=it_special)


# ---- special items ---------------------------------------------------------------------------------------------------
def sp_dobber(ctx, it):
    x, y = it['u'], it['v']
    V, F = g_cyl(0.0065, 0.0065, 0.0, 0.0025, n=20, cap0=False, x=x, y=y)
    ctx.add(V, F, 'lgray', orient=False)
    V, F = g_box(x - 0.003, y - 0.0045, 0.0025, x + 0.003, y + 0.0045, 0.010)
    ctx.add(V, F, 'lgray')


def sp_jettison(ctx, it):
    x, y = it['u'], it['v']
    V, F = g_box(x - 0.020, y - 0.020, 0.0, x + 0.020, y + 0.020, 0.003)
    ctx.add(V, F, 'black')
    V, F = g_cyl(0.0125, 0.0125, 0.0, 0.009, n=24, cap0=False, x=x, y=y)
    ctx.add(V, F, 'black', orient=False)


def sp_gearhandle(ctx, it):
    x, y = it['u'], it['v']
    # slot plate, lever (down position) and the wheel-shaped knob
    V, F = g_box(x - 0.006, y - 0.052, 0.0, x + 0.006, y + 0.034, 0.002)
    ctx.add(V, F, 'black')
    p0 = np.array([x, y - 0.036, 0.002])
    p1 = p0 + np.array([0.0, -0.004, 0.048])
    V, F = g_tube([p0, p1], 0.0042, n=10)
    ctx.add(V, F, 'metal', art_front=False, orient=False)
    # knob: a thick disc shaped like a wheel, axis along u (vertical wheel facing sideways)
    V, F = g_cyl(0.0165, 0.0165, -0.008, 0.008, n=28)
    V = V[:, [2, 1, 0]]
    V = V + p1 + np.array([0.0, 0.0, 0.010])
    ctx.add(V, F, 'white', art_front=False)
    V, F = g_cyl(0.0105, 0.0105, -0.0085, 0.0085, n=20)
    V = V[:, [2, 1, 0]]
    V = V + p1 + np.array([0.0, 0.0, 0.010])
    ctx.add(V, F, 'red', art_front=False)
    # DN LOCK REL button already a key; small warning placard is painted


def sp_fuelflow(ctx, it):
    x, y = it['u'], it['v']
    V, F = g_rrect_prism(0.060, 0.034, 0.003, 0.0, 0.010, n=2, x=x, y=y)
    ctx.add(V, F, 'black', orient=False)


def sp_throttle_slot(ctx, it):
    pass     # the throttle itself is built in build_throttle(); the slot is painted


def sp_stick_base(ctx, it):
    x, y = it['u'], it['v']
    V, F = g_rrect_prism(0.070, 0.085, 0.012, 0.0, 0.012, n=3, x=x, y=y)
    ctx.add(V, F, 'black', orient=False)


def sp_uhf(ctx, it):
    x, y = it['u'], it['v']
    # frequency readout window + preset channel window + 5 frequency selector knobs
    V, F = g_rrect_prism(0.072, 0.016, 0.002, 0.0, 0.004, n=1, x=x - 0.020, y=y + 0.012)
    ctx.add(V, F, 'black', orient=False)
    for i in range(5):
        V, F = g_fluted(0.0055, 0.0, 0.010, flutes=12, x=x - 0.050 + i * 0.019, y=y - 0.010)
        ctx.add(V, F, 'black', orient=False)
    V, F = g_fluted(0.008, 0.0, 0.012, flutes=14, x=x + 0.052, y=y + 0.008)
    ctx.add(V, F, 'black', orient=False)


def sp_oxyreg(ctx, it):
    x, y = it['u'], it['v']
    # flow indicator + pressure gauge, three lever switches (SUPPLY / DILUTER / EMERGENCY)
    V, F = g_flange(0.030, 0.036, 0.036, 0.0, 0.006, 0.0, n=28, x=x - 0.040, y=y + 0.022)
    ctx.add(V, F, 'black', orient=False)
    V, F = g_flange(0.030, 0.036, 0.036, 0.0, 0.006, 0.0, n=28, x=x + 0.0, y=y + 0.022)
    ctx.add(V, F, 'black', orient=False)
    for i, col in enumerate(('green', 'white', 'red')):
        bx = x - 0.045 + i * 0.030
        V, F = g_box(bx - 0.004, y - 0.040, 0.0, bx + 0.004, y - 0.012, 0.004)
        ctx.add(V, F, 'black')
        V, F = g_box(bx - 0.0035, y - 0.026, 0.004, bx + 0.0035, y - 0.012, 0.011)
        ctx.add(V, F, 'lever_' + col if col != 'white' else 'metal', art_front=False)


SPECIALS = dict(dobber=sp_dobber, jettison=sp_jettison, gearhandle=sp_gearhandle, fuelflow=sp_fuelflow,
                throttle_slot=sp_throttle_slot, stick_base=sp_stick_base, uhf=sp_uhf, oxyreg=sp_oxyreg)


# ----------------------------------------------------------------------------------------------------------------------
# structure (drawing frame)
COCKPIT_C = np.array((4.15, 0.0, 2.35))


def add_world(parts, key, V, F, lite=False, orient=True, center=None, toward=None):
    """orient: faces point away from the centroid (closed convex solids); toward: faces point toward a point (sheets)."""
    V = np.asarray(V, float)
    if toward is not None:
        T = np.asarray(toward, float)
        out = []
        for f in F:
            P = V[list(f)]
            out.append(tuple(f) if np.dot(face_normal(P), T - P.mean(0)) >= 0 else tuple(f)[::-1])
        F = out
    elif orient:
        F = orient_out(V, F, center)
    parts.add('m:' + key, V, F, None, lite=lite)


def grid_faces(nr, nc):
    return [(i * nc + j, i * nc + j + 1, (i + 1) * nc + j + 1, (i + 1) * nc + j) for i in range(nr - 1) for j in range(nc - 1)]


def canopy_upper(s, y):
    """Height of the canopy glass (upper branch of its section) at station s, |y| (drawing frame)."""
    pts = np.asarray(PT.canopy_section(s, n=(10, 10, 6)))
    w = pts[:, 0]
    k = int(np.argmax(w))
    up = pts[:k + 1]
    return float(np.interp(abs(y), up[:, 0], up[:, 1]))


def build_glareshield(parts):
    """Anti-glare hood: top surface from the rear lip to the windscreen (flat over the ICP / RWR / DED, sloping
    'eyebrow' shoulders down to the canopy sills - the pilot's-view outline of the F-16C glareshield), lip fascia."""
    ne, nt = 41, 14
    S_FRONT = 3.12
    V = []
    for i in range(nt):
        t = i / (nt - 1)
        for j in range(ne):
            eta = -1 + 2 * j / (ne - 1)
            w = CL.LIP_W * (1 - t) + 0.318 * t
            y = eta * w
            s0 = CL.lip_s(y)
            s = s0 + t * (S_FRONT - s0)
            zc = CL.LIP_Z - 0.30 * t * (CL.LIP_S + CL.ICP_PROUD - S_FRONT)
            fl = CL.LIP_FLAT * (1 - t) + 0.13 * t
            z = zc - (zc - CL.SILL_Z + 0.02 * (1 - t)) * CL.lip_profile(y, fl, w)
            # keep 3 cm inside the canopy glass
            z = min(z, canopy_upper(s, y) - 0.03)
            V.append((s, y, z))
    F = grid_faces(nt, ne)
    Vn = np.array(V)
    F = [f if face_normal(Vn[list(f)])[2] > 0 else f[::-1] for f in F]
    parts.add('m:glare', Vn, F, None, lite=True)
    # lip fascia: 18 mm band under the lip, facing the pilot
    top = Vn[:ne]
    bot = top + np.array([0.004, 0.0, -0.018])
    Vf = np.concatenate([top, bot])
    Ff = [(j, j + 1, ne + j + 1, ne + j) for j in range(ne - 1)]
    Ff = [f if face_normal(Vf[list(f)])[0] > 0 else f[::-1] for f in Ff]
    parts.add('m:glare', Vf, Ff, None, lite=True)
    # underside back toward the bulkhead (hidden) so the hood looks solid from the sides
    under = bot + np.array([-0.10, 0.0, 0.0])
    Vu = np.concatenate([bot, under])
    Fu = [(j, j + 1, ne + j + 1, ne + j) for j in range(ne - 1)]
    Fu = [f if face_normal(Vu[list(f)])[2] < 0 else f[::-1] for f in Fu]
    parts.add('m:panel', Vu, Fu, None)


def build_hud(parts):
    """HUD combiner assembly on the glareshield (side frames, top bar, glass) + indexers + HUD camera."""
    yf = 0.115                   # side frames
    zt = 2.872                   # top bar
    s_rear = 3.642
    s_fb, z_fb = 3.470, CL.glare_top_z(3.470) + 0.004       # front-bottom of the glass
    s_ft = 3.598                 # front-top
    for sg in (-1, 1):
        y = sg * yf
        # rear post: tapered box
        V = [(s_rear - 0.024, y - 0.005, CL.glare_top_z(s_rear - 0.024) - 0.01), (s_rear, y - 0.005, CL.LIP_Z - 0.01),
             (s_rear, y - 0.005, zt), (s_rear - 0.014, y - 0.005, zt),
             (s_rear - 0.024, y + 0.005, CL.glare_top_z(s_rear - 0.024) - 0.01), (s_rear, y + 0.005, CL.LIP_Z - 0.01),
             (s_rear, y + 0.005, zt), (s_rear - 0.014, y + 0.005, zt)]
        F = [(0, 1, 2, 3), (4, 7, 6, 5), (0, 4, 5, 1), (1, 5, 6, 2), (2, 6, 7, 3), (3, 7, 4, 0)]
        add_world(parts, 'hudframe', V, F, lite=True)
        # front bar (glass edge frame)
        Vt, Ft = g_tube([(s_fb, y, z_fb), (s_ft, y, zt - 0.004)], 0.0032, n=8)
        add_world(parts, 'hudframe', Vt, Ft, lite=True, orient=False)
        # lower side plate between the front bar foot and the rear post (solid base)
        V = [(s_fb, y - 0.006, z_fb - 0.01), (s_rear - 0.03, y - 0.006, CL.glare_top_z(s_rear - 0.03) - 0.01),
             (s_rear - 0.03, y - 0.006, CL.glare_top_z(s_rear - 0.03) + 0.045), (s_fb + 0.02, y - 0.006, z_fb + 0.035),
             (s_fb, y + 0.006, z_fb - 0.01), (s_rear - 0.03, y + 0.006, CL.glare_top_z(s_rear - 0.03) - 0.01),
             (s_rear - 0.03, y + 0.006, CL.glare_top_z(s_rear - 0.03) + 0.045), (s_fb + 0.02, y + 0.006, z_fb + 0.035)]
        add_world(parts, 'hudframe', V, F, lite=True)
    # top bar (slightly arched)
    pts = [(s_rear - 0.012, t * yf * 1.02, zt + 0.010 * (1 - t * t)) for t in np.linspace(-1, 1, 9)]
    Vt, Ft = g_tube(pts, 0.0045, n=8)
    add_world(parts, 'hudframe', Vt, Ft, lite=True, orient=False)
    Vt, Ft = g_tube([(s_ft, -yf, zt - 0.004), (s_ft, yf, zt - 0.004)], 0.003, n=8)
    add_world(parts, 'hudframe', Vt, Ft, lite=True, orient=False)
    # combiner glass (tinted plate between the front bars)
    g = [(s_fb, -yf + 0.004, z_fb), (s_fb, yf - 0.004, z_fb), (s_ft, yf - 0.004, zt - 0.004), (s_ft, -yf + 0.004, zt - 0.004)]
    parts.glass.setdefault('hud_glass', []).append(np.array(g))
    # base box of the HUD between the frames (dark) sitting on the glareshield
    V, F = g_box(s_fb - 0.01, -yf, 0.0, s_rear - 0.03, yf, 1.0)
    V = np.array([(p[0], p[1], CL.glare_top_z(p[0]) - 0.02 + (0.012 if p[2] > 0.5 else 0.0)) for p in V])
    add_world(parts, 'hudframe', V, F, lite=True)
    # screen_hud: vertical quad at s_scr spanning +5.5 .. -15 deg, +-9.5 deg from the eye
    E = CL.EYE
    s_scr = 3.545
    dist = E[0] - s_scr
    zt_s = E[2] + dist * math.tan(math.radians(5.5))
    zb_s = E[2] - dist * math.tan(math.radians(15.0))
    hw = dist * math.tan(math.radians(9.3))
    Vs = [(s_scr, -hw, zb_s), (s_scr, hw, zb_s), (s_scr, hw, zt_s), (s_scr, -hw, zt_s)]
    parts.screens['screen_hud'] = _single(Vs, [(0, 1, 2, 3)], [[(0, 1), (1, 1), (1, 0), (0, 0)]], 'screen_hud')
    # AOA indexer (left) and AR status indexer (right): small boxes on the glareshield next to the combiner
    for sg in (-1, 1):
        y = sg * 0.150
        s0 = 3.625
        zb = CL.glare_top_z(s0 - 0.015) - 0.006
        V, F = g_box(s0 - 0.030, y - 0.012, zb, s0, y + 0.012, zb + 0.070)
        add_world(parts, 'hudframe', V, F, lite=True)
        for k in range(3):
            Vc, Fc = g_cyl(0.0048, 0.0048, 0.0, 0.004, n=12)
            Vc = Vc[:, [2, 0, 1]] + np.array([s0, y, zb + 0.056 - k * 0.018])
            add_world(parts, 'lens_' + ('amber' if k == 0 else 'green' if k == 1 else 'red'), Vc, Fc)
    # HUD camera (forward right of the combiner base)
    Vc, Fc = g_cyl(0.011, 0.011, 0.0, 0.055, n=16)
    Vc = Vc[:, [2, 0, 1]] * np.array([-1, 1, 1]) + np.array([3.530, 0.060, CL.glare_top_z(3.53) + 0.014])
    add_world(parts, 'hudframe', Vc, Fc)


def build_structure(parts):
    """Bulkhead behind the panels, ICP housing, pedestal, knee wells, floor, side walls, sill rails, pedals."""
    Z0 = CL.FLOOR_Z
    C = COCKPIT_C
    # forward bulkhead behind the panels (closes every gap between the panel planes); top follows the glareshield lip
    ys = np.linspace(-0.405, 0.405, 25)
    top = [(3.63, y, CL.lip_z(y) - 0.02) for y in ys]
    bot = [(3.63, y, Z0) for y in ys]
    Vb = np.array(bot + top)
    n = len(ys)
    add_world(parts, 'panel', Vb, [(i, i + 1, n + i + 1, n + i) for i in range(n - 1)], toward=(4.2, 0, 2.3))
    # ICP housing underside: from the ICP bottom edge back to the column top
    icp = CL.PANELS['icp']['f']; cs = CL.PANELS['cstack']['f']
    hw, hh = CL.ICP_W / 2, CL.ICP_H / 2
    a0 = icp.p(-hw, -hh); a1 = icp.p(hw, -hh)
    b0 = cs.p(-0.10, 0.16); b1 = cs.p(0.10, 0.16)
    add_world(parts, 'panel', [a0, a1, b1, b0], [(0, 1, 2, 3)], lite=True, toward=(4.3, 0, 2.2))
    # ICP housing side walls back into the glareshield
    for sg in (-1, 1):
        p = [icp.p(sg * hw, hh), icp.p(sg * hw, -hh), cs.p(sg * 0.10, 0.16),
             (3.60, sg * hw, 2.46), (3.60, sg * hw, 2.64)]
        add_world(parts, 'panel', p, [(0, 1, 2, 3, 4)], lite=True, toward=(3.7, sg * 0.4, 2.55))
    # center pedestal below the column down to the floor (between the knees)
    b0 = cs.p(-0.10, -0.16); b1 = cs.p(0.10, -0.16)
    PS = 3.70           # the pedestal's foot (station) - it slopes forward so the seat and ejection handle clear it
    V = [b0, b1, (PS, 0.07, Z0 + 0.12), (PS, -0.07, Z0 + 0.12)]
    add_world(parts, 'panel', V, [(0, 1, 2, 3)], lite=True, toward=(4.3, 0, 2.3))
    for sg in (-1, 1):
        bb = b1 if sg > 0 else b0
        V = [bb, (PS, sg * 0.07, Z0 + 0.12), (3.63, sg * 0.07, Z0 + 0.12), (3.63, sg * 0.10, bb[2])]
        add_world(parts, 'panel', V, [(0, 1, 2, 3)], toward=(3.75, sg * 0.3, 2.1))
    # recorder / standby compass box at the foot of the center column (dark box with a round lens housing)
    b0v, b1v = np.array(b0), np.array(b1)
    top = (b0v + b1v) / 2
    foot = np.array((PS, 0.0, Z0 + 0.12))
    vdir = (top - foot) / np.linalg.norm(top - foot)
    nrm = np.cross(np.array((0.0, 1.0, 0.0)), vdir); nrm /= np.linalg.norm(nrm)
    if nrm[0] < 0:
        nrm = -nrm
    A = np.array([(0.0, 1.0, 0.0), vdir, nrm])
    c0 = top - vdir * 0.055
    V, F = g_box(-0.034, -0.026, -0.03, 0.034, 0.026, 0.012)
    add_world(parts, 'black', c0 + V @ A, F)
    Vc, Fc = g_cyl(0.019, 0.017, 0.0, 0.016, n=24)
    add_world(parts, 'black', c0 + nrm * 0.012 + Vc @ A, Fc)
    Vc, Fc = g_cyl(0.013, 0.013, 0.0, 0.003, n=24)
    add_world(parts, 'lens_green', c0 + nrm * 0.027 + Vc @ A, Fc)
    # knee-well roofs under the MFD wings (dark)
    for sg in (-1, 1):
        mf = CL.PANELS['lmfd' if sg < 0 else 'rmfd']['f']
        a = mf.p(-0.08, -0.075); b = mf.p(0.08, -0.075)
        V = [a, b, (b[0] - 0.12, b[1], b[2] - 0.02), (a[0] - 0.12, a[1], a[2] - 0.02)]
        add_world(parts, 'panel', V, [(0, 1, 2, 3)], toward=(3.7, sg * 0.18, 2.0))
    # floor
    V = [(3.05, -0.36, Z0), (4.98, -0.36, Z0), (4.98, 0.36, Z0), (3.05, 0.36, Z0)]
    add_world(parts, 'floor', V, [(0, 1, 2, 3)], toward=(4.0, 0, 3.0))
    # footwell side walls forward of the consoles (floor -> sill)
    for sg in (-1, 1):
        V = [(3.10, sg * 0.34, Z0), (3.845, sg * 0.36, Z0), (3.845, sg * 0.405, CL.SILL_Z - 0.01), (3.10, sg * 0.33, CL.SILL_Z - 0.01)]
        add_world(parts, 'wall', V, [(0, 1, 2, 3)], toward=(3.5, 0, 2.2))
    for sg in (-1, 1):
        s0, s1, yi, yo, zt = CL.CONS_S0, CL.CONS_S1, CL.CONS_YI * sg, CL.CONS_YO * sg, CL.CONSOLE_Z
        # rounded console edge trim (inboard lip)
        Vt, Ft = g_tube([(s0, yi, zt - 0.004), (s1, yi, zt - 0.004)], 0.006, n=8)
        add_world(parts, 'panel', Vt, Ft, orient=False)
        # side wall above the console up to the sill
        S = np.linspace(3.845, 5.05, 14)
        top = [(s, sg * (min(PT.glass_edge_w(s) - 0.025, 0.405)), FU.surface_point(s, PT.glass_edge_w(s)) - 0.03) for s in S]
        bot = [(s, sg * min(PT.glass_edge_w(s) - 0.025, 0.405), zt if s <= s1 else Z0 + 0.25) for s in S]
        Vw = np.array(bot + top)
        n = len(S)
        add_world(parts, 'wall', Vw, [(i, i + 1, n + i + 1, n + i) for i in range(n - 1)], lite=True, toward=C)
        # aft of the console: the wall continues down to the floor
        Va = [(s1, sg * CL.CONS_YI, Z0), (4.95, sg * CL.CONS_YI, Z0), (4.95, sg * 0.40, Z0 + 0.25), (s1, sg * 0.404, Z0 + 0.25)]
        add_world(parts, 'wall', Va, [(0, 1, 2, 3)], toward=C)
        # canopy sill rail (longeron cap) with the seal: a rounded bar along the sill
        S2 = np.linspace(3.10, 5.10, 24)
        path = [(s, sg * (PT.glass_edge_w(s) - 0.028), FU.surface_point(s, PT.glass_edge_w(s)) - 0.018) for s in S2]
        Vt, Ft = g_tube(path, 0.014, n=10)
        add_world(parts, 'rail', Vt, Ft, lite=True, orient=False)
        seal = [(s, sg * (PT.glass_edge_w(s) - 0.014), FU.surface_point(s, PT.glass_edge_w(s)) - 0.004) for s in S2]
        Vt, Ft = g_tube(seal, 0.005, n=6)
        add_world(parts, 'rubber', Vt, Ft, orient=False)
    V = [(4.95, -0.40, Z0), (4.95, 0.40, Z0), (4.95, 0.34, 2.62), (4.95, -0.34, 2.62)]
    add_world(parts, 'wall', V, [(0, 1, 2, 3)], toward=(4.0, 0, 2.4))
    # rudder pedals (under the panel)
    for sg in (-1, 1):
        y = sg * 0.12
        ax = ((1, 0, 0.35), (0, 1, 0), (-0.35, 0, 1))
        c = np.array((3.20, y, 2.04))
        V, F = g_box(-0.012, -0.045, -0.085, 0.012, 0.045, 0.085)
        A = np.array([np.array(a) / np.linalg.norm(a) for a in ax])
        add_world(parts, 'metal', c + V @ A, F)
        Vt, Ft = g_tube([(3.10, y, 1.96), (3.19, y, 2.03)], 0.011, n=8)
        add_world(parts, 'metal', Vt, Ft, orient=False)
    # canopy manual handle on the right wall, forward of the console
    s0 = 3.80
    y = 0.395
    Vt, Ft = g_tube([(s0, y, 2.33), (s0 + 0.01, y - 0.03, 2.33), (s0 + 0.13, y - 0.03, 2.34)], 0.007, n=10)
    add_world(parts, 'metal', Vt, Ft, orient=False)
    V, F = g_box(s0 - 0.02, y - 0.004, 2.30, s0 + 0.03, y + 0.004, 2.37)
    add_world(parts, 'metal', V, F)


# ----------------------------------------------------------------------------------------------------------------------
def _loft(sections, cap0=True, cap1=True):
    """sections: list of (N,3) rings with the same N. Returns V, F."""
    S = [np.asarray(s, float) for s in sections]
    n = len(S[0])
    V = np.concatenate(S)
    F = []
    for i in range(len(S) - 1):
        for k in range(n):
            a, b = i * n + k, i * n + (k + 1) % n
            F.append((a, b, b + n, a + n))
    if cap0:
        F.append(tuple(range(n))[::-1])
    if cap1:
        F.append(tuple(range((len(S) - 1) * n, len(S) * n)))
    return V, F


def _ellipse(c, ax1, ax2, r1, r2, n=16, sq=2.0):
    c = np.asarray(c, float); ax1 = np.asarray(ax1, float); ax2 = np.asarray(ax2, float)
    ax1 = ax1 / np.linalg.norm(ax1); ax2 = ax2 / np.linalg.norm(ax2)
    out = []
    for k in range(n):
        a = TAU * k / n
        ca, sa = math.cos(a), math.sin(a)
        # superellipse for a boxier grip section
        cx = math.copysign(abs(ca) ** (2 / sq), ca)
        sy = math.copysign(abs(sa) ** (2 / sq), sa)
        out.append(c + r1 * cx * ax1 + r2 * sy * ax2)
    return np.array(out)


def build_stick(parts):
    """F-16 force sidestick (right console): boot, grip with trigger, pickle button, hat switches."""
    s0, y0, z0 = CL.STICK['s'], CL.STICK['y'], CL.CONSOLE_Z + 0.012
    # boot
    Vb, Fb = g_lathe([(0.026, 0.0), (0.024, 0.010), (0.018, 0.022), (0.015, 0.030)], n=16)
    add_world(parts, 'rubber', Vb + np.array([s0 + 0.01, y0, z0]), Fb, lite=True, orient=False)
    # grip: sections along a slightly forward-leaning axis (the grip is canted ~ 12 deg forward, 8 deg inboard)
    axis_dir = np.array([-0.20, -0.09, 1.0]); axis_dir /= np.linalg.norm(axis_dir)
    fwd = np.array([-1.0, 0, 0]); fwd = fwd - axis_dir * np.dot(fwd, axis_dir); fwd /= np.linalg.norm(fwd)
    side = np.cross(axis_dir, fwd)
    base = np.array([s0 + 0.01, y0, z0 + 0.028])
    prof = [(0.000, 0.016, 0.014, 0.0), (0.015, 0.019, 0.016, 0.0), (0.035, 0.023, 0.018, 0.0), (0.060, 0.024, 0.019, 0.0),
            (0.085, 0.023, 0.019, 0.002), (0.100, 0.024, 0.019, 0.006), (0.112, 0.032, 0.021, 0.014), (0.126, 0.037, 0.022, 0.018),
            (0.140, 0.036, 0.021, 0.018), (0.150, 0.030, 0.018, 0.014), (0.156, 0.018, 0.012, 0.010)]
    secs = []
    for t, rf, rs, off in prof:
        c = base + axis_dir * t + fwd * off
        secs.append(_ellipse(c, fwd, side, rf, rs, n=18, sq=2.6))
    V, F = _loft(secs)
    add_world(parts, 'stick', V, F, lite=True, orient=False)
    top = base + axis_dir * 0.150
    # trigger (front, curved paddle)
    tp = [base + axis_dir * 0.108 + fwd * 0.036, base + axis_dir * 0.094 + fwd * 0.044, base + axis_dir * 0.078 + fwd * 0.040]
    Vt, Ft = g_tube(tp, 0.0045, n=8)
    add_world(parts, 'stick', Vt, Ft, orient=False)
    # pickle button (red) on top-left, trim hat, TMS / DMS hats
    def button(center, dirn, r, h, mat, n=12):
        dirn = np.asarray(dirn, float); dirn /= np.linalg.norm(dirn)
        Vc, Fc = g_cyl(r, r, 0.0, h, n=n)
        a = np.array([0, 0, 1.0]); vv = np.cross(a, dirn); sn = np.linalg.norm(vv); cs = np.dot(a, dirn)
        if sn < 1e-9:
            R = np.eye(3)
        else:
            k = vv / sn
            K = np.array([[0, -k[2], k[1]], [k[2], 0, -k[0]], [-k[1], k[0], 0]])
            R = np.eye(3) + sn * K + (1 - cs) * K @ K
        add_world(parts, mat, Vc @ R.T + center, Fc, orient=False)
    top = base + axis_dir * 0.152 + fwd * 0.012
    button(top + side * (-0.010) + fwd * 0.022, axis_dir + fwd * 0.3, 0.0055, 0.009, 'red')          # weapon release
    button(top + side * 0.006 + fwd * 0.004, axis_dir, 0.0068, 0.008, 'stickhat')                    # trim
    button(top + fwd * (-0.012) + side * (-0.004) - axis_dir * 0.008, -fwd + axis_dir * 0.7, 0.0055, 0.008, 'stickhat')   # TMS
    button(base + axis_dir * 0.112 + fwd * 0.006 + side * 0.020, side + axis_dir * 0.3, 0.0048, 0.007, 'stickhat')          # DMS
    button(base + axis_dir * 0.128 + side * (-0.024) + fwd * 0.002, -side, 0.005, 0.007, 'stickhat')
    # pinky / NWS button and paddle switch
    button(base + axis_dir * 0.040 + fwd * 0.024, fwd, 0.004, 0.006, 'stickhat')
    Vp, Fp = g_box(-0.004, -0.012, -0.002, 0.004, 0.012, 0.002)
    add_world(parts, 'metal', Vp + base + axis_dir * 0.020 + fwd * 0.030, Fp)
    # armrest behind the stick (padded, inboard)
    s1 = s0 + 0.075
    V, F = g_box(s1, y0 - 0.040, CL.CONSOLE_Z + 0.0, s1 + 0.17, y0 + 0.010, CL.CONSOLE_Z + 0.045)
    add_world(parts, 'cushion', V, F, lite=True)


def build_throttle(parts):
    """Throttle (left console): quadrant slot, lever, grip with HOTAS switches."""
    s0, y0 = CL.THROTTLE['s'], CL.THROTTLE['y']
    zt = CL.CONSOLE_Z
    # lever from the slot
    p0 = np.array([s0 + 0.025, y0, zt - 0.02])
    p1 = np.array([s0 + 0.005, y0 - 0.005, zt + 0.055])
    Vt, Ft = g_tube([p0, p1], 0.008, n=10)
    add_world(parts, 'metal', Vt, Ft, orient=False)
    # grip: a mouse-like body lying fore-aft (hand on top, fingers over the front), lofted along -s
    zb = p1[2] - 0.006
    prof = [  # (s offset from the lever top, half width, bottom z, top z)
        (0.050, 0.020, 0.006, 0.030), (0.035, 0.028, 0.000, 0.058), (0.015, 0.031, -0.004, 0.078), (-0.010, 0.032, -0.006, 0.090),
        (-0.035, 0.031, -0.004, 0.098), (-0.060, 0.029, 0.004, 0.104), (-0.080, 0.026, 0.016, 0.104), (-0.094, 0.020, 0.032, 0.094),
        (-0.101, 0.010, 0.050, 0.080)]
    secs = []
    for ds, hw, z0, z1 in prof:
        c = np.array([p1[0] + ds, p1[1] + 0.004, zb + (z0 + z1) / 2])
        secs.append(_ellipse(c, np.array([0, 0, 1.0]), np.array([0, 1.0, 0]), (z1 - z0) / 2, hw, n=20, sq=2.8))
    V, F = _loft(secs)
    add_world(parts, 'stick', V, F, lite=True, orient=False)
    fwd = np.array([-1.0, 0, 0]); up = np.array([0, 0, 1.0]); side = np.array([0, 1.0, 0])
    base = np.array([p1[0], p1[1] + 0.004, zb])

    def cylat(center, dirn, r, h, mat, n=12):
        dirn = np.asarray(dirn, float); dirn /= np.linalg.norm(dirn)
        Vc, Fc = g_cyl(r, r, 0.0, h, n=n)
        a = np.array([0, 0, 1.0]); vv = np.cross(a, dirn); sn = np.linalg.norm(vv); cs = np.dot(a, dirn)
        if sn < 1e-9:
            R = np.eye(3)
        else:
            k = vv / sn
            K = np.array([[0, -k[2], k[1]], [k[2], 0, -k[0]], [-k[1], k[0], 0]])
            R = np.eye(3) + sn * K + (1 - cs) * K @ K
        add_world(parts, mat, Vc @ R.T + center, Fc, orient=False)
    cylat(base + fwd * 0.078 + up * 0.100, fwd * 0.6 + up, 0.0085, 0.010, 'stickhat', n=16)          # MAN RNG / UNCAGE
    cylat(base + fwd * 0.055 + up * 0.104, up, 0.0055, 0.008, 'stickhat')                             # comm switch
    cylat(base + fwd * 0.090 + up * 0.080 + side * 0.012, fwd, 0.0075, 0.006, 'stickhat', n=16)       # antenna elevation
    cylat(base + fwd * 0.094 + up * 0.060 + side * 0.016, fwd, 0.0042, 0.008, 'stickhat')             # dogfight
    cylat(base + fwd * 0.050 + up * 0.060 + side * 0.031, side, 0.0055, 0.007, 'stickhat')            # cursor enable/slew
    cylat(base + fwd * 0.030 + up * 0.080 + side * 0.030, side, 0.0045, 0.006, 'stickhat')            # speed brake
    cylat(base + fwd * 0.080 + up * 0.030 + side * 0.020, fwd, 0.004, 0.010, 'stickhat')              # black-out switch
    # quadrant slot rails
    L0, L1 = CL.THROTTLE['slot']
    for dy in (-0.012, 0.012):
        V, F = g_box(L0, y0 + dy - 0.002, zt, L1, y0 + dy + 0.002, zt + 0.006)
        add_world(parts, 'black', V, F)


def build_seat(parts):
    """ACES II ejection seat (reclined 30 deg): bucket, back, headbox + drogue/pitots, cushions, harness, ejection handle."""
    hs, _, hz = OLD.SEAT_HIP
    ang = OLD.SEAT_BACK
    up = np.array((math.sin(ang), 0.0, math.cos(ang)))
    fwd = np.array((-math.cos(ang), 0.0, math.sin(ang)))
    side = np.array((0.0, 1.0, 0.0))
    H = np.array((hs, 0.0, hz))

    def obox(mat, c, size, axes, lite=False):
        A = np.array([np.asarray(a, float) / np.linalg.norm(a) for a in axes])
        V, F = g_box(-size[0] / 2, -size[1] / 2, -size[2] / 2, size[0] / 2, size[1] / 2, size[2] / 2)
        add_world(parts, mat, np.asarray(c) + V @ A, F, lite=lite)

    BA = (fwd, side, up)
    # back structure + back cushion (with vertical quilting via 3 pads)
    obox('seatframe', H + up * 0.40 - fwd * 0.095, (0.05, 0.46, 0.82), BA, lite=True)
    for k, yy in enumerate((-0.12, 0.0, 0.12)):
        obox('cushion', H + up * 0.33 - fwd * 0.045 + side * yy, (0.055, 0.115, 0.50), BA, lite=True)
    # headbox (parachute container) + headrest pad + canopy breakers
    obox('headbox', H + up * 0.74 - fwd * 0.125, (0.17, 0.43, 0.30), BA, lite=True)
    obox('cushion', H + up * 0.77 - fwd * 0.030, (0.06, 0.26, 0.17), BA, lite=True)
    obox('seatframe', H + up * 0.895 - fwd * 0.125, (0.18, 0.44, 0.02), BA, lite=True)
    for sg in (-1, 1):
        # canopy breakers / pitot booms on the headbox top
        p0 = H + up * 0.90 - fwd * 0.16 + side * sg * 0.17
        Vt, Ft = g_tube([p0, p0 + up * 0.11 + fwd * 0.03], 0.0055, n=8)
        add_world(parts, 'metal', Vt, Ft, orient=False)
        p0 = H + up * 0.90 - fwd * 0.09 + side * sg * 0.07
        Vt, Ft = g_tube([p0, p0 + up * 0.035], 0.012, n=10)
        add_world(parts, 'seatframe', Vt, Ft, orient=False)
        # side rails of the back (bucket extensions) and the guide rails behind
        obox('seatframe', H + up * 0.30 - fwd * 0.080 + side * sg * 0.222, (0.07, 0.028, 0.58), BA, lite=True)
        r0 = H + up * 0.02 - fwd * 0.18 + side * sg * 0.13
        Vt, Ft = g_tube([r0, r0 + up * 0.86], 0.013, n=8)
        add_world(parts, 'metal', Vt, Ft, orient=False)
        # shoulder harness straps from the headbox down the back cushion
        a = H + up * 0.62 - fwd * 0.012 + side * sg * 0.085
        c = H + up * 0.08 + fwd * 0.012 + side * sg * 0.105
        m = (a + c) / 2
        obox('strap', m, (0.006, 0.045, np.linalg.norm(a - c)), (fwd, side, a - c))
    # seat pan: survival kit + cushion, raised front
    pan = ((1, 0, -0.14), (0, 1, 0), (0.14, 0, 1))
    # (the pan ends ~10 cm short of the knees; the ejection handle sits just aft of the center pedestal)
    obox('seatframe', (hs - 0.055, 0, hz - 0.075), (0.36, 0.44, 0.11), pan, lite=True)
    obox('fur', (hs - 0.06, 0, hz - 0.005), (0.33, 0.38, 0.05), pan, lite=True)
    obox('kit', (hs - 0.08, 0, hz - 0.145), (0.26, 0.30, 0.05), pan)
    for sg in (-1, 1):
        obox('seatframe', (hs - 0.05, sg * 0.228, hz + 0.02), (0.36, 0.026, 0.21), ((1, 0, 0), (0, 1, 0), (0, 0, 1)), lite=True)
        obox('black', (hs - 0.14, sg * 0.232, hz + 0.135), (0.14, 0.032, 0.028), ((1, 0, 0), (0, 1, 0), (0, 0, 1)))
        # lap belt halves
        obox('strap', (hs - 0.08, sg * 0.14, hz + 0.05), (0.05, 0.12, 0.006), ((1, 0, 0.3), (0, 1, 0), (-0.3, 0, 1)))
    obox('metal', (hs - 0.09, 0, hz + 0.066), (0.06, 0.07, 0.014), ((1, 0, 0.3), (0, 1, 0), (-0.3, 0, 1)))
    # ejection handle: yellow/black striped loop at the front of the seat bucket
    pts = []
    R = 0.045
    cx, cz = hs - 0.225, hz + 0.03
    for k in range(25):
        a = math.pi * k / 24
        pts.append((cx - 0.012 * math.sin(a), -R * math.cos(a), cz + 0.05 * math.sin(a) ** 0.7))
    for k in range(len(pts) - 1):
        Vt, Ft = g_tube([pts[k], pts[k + 1]], 0.0075, n=8, caps=False)
        add_world(parts, 'yellow' if (k // 2) % 2 == 0 else 'black', Vt, Ft, orient=False)
    for sg in (-1, 1):
        Vt, Ft = g_tube([(cx, sg * R, cz), (cx + 0.03, sg * R, cz - 0.03)], 0.0075, n=8)
        add_world(parts, 'yellow', Vt, Ft, orient=False)
    # emergency manual chute handle (left side of the seat bucket) and shoulder harness lock (small ball knob)
    Vt, Ft = g_tube([(hs - 0.16, -0.245, hz + 0.08), (hs - 0.20, -0.245, hz + 0.10), (hs - 0.20, -0.245, hz + 0.05)], 0.006, n=8)
    add_world(parts, 'yellow', Vt, Ft, orient=False)
    Vs, Fs = g_lathe([(0.0, -0.01), (0.008, -0.006), (0.009, 0.0), (0.008, 0.006), (0.0, 0.01)], n=12)
    add_world(parts, 'black', Vs + np.array([hs - 0.15, -0.248, hz + 0.16]), Fs, orient=False)


# ----------------------------------------------------------------------------------------------------------------------
def build():
    CL.build_layout()
    parts = Parts()
    for name, P in CL.PANELS.items():
        build_panel(parts, P)
    build_glareshield(parts)
    build_hud(parts)
    build_structure(parts)
    build_stick(parts)
    build_throttle(parts)
    build_seat(parts)
    md = parts.meshdata()
    screens = parts.screens
    glass = {}
    for k, rings in parts.glass.items():
        V, F = [], []
        for r in rings:
            off = len(V)
            V.extend(list(r))
            F.append(tuple(range(off, off + len(r))))
        Vn = np.array(V)
        glass[k] = MeshData(to_blender(Vn[:, 0], Vn[:, 1], Vn[:, 2]), F, None, k)
    return md, screens, glass
